version: '3.8'
services:
  db:
    image: mariadb:10.6.11-focal
    ports:
      - '3306:3006'
    restart: always
    environment:
      - MARIADB_DATABASE: blog
      - MARIADB_ROOT_PASSWORD: secret
    volumes:
      - db:/var/lib/mariadb/data
  cache:
    image: redis:6.2.8-alpine3.17
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass secret
    volumes:
      - cache:/var/lib/redis/data
volumes:
  db:
    driver: local
  cache:
    driver: local
