// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package http is a generated GoMock package.
package http

import (
	gomock "github.com/golang/mock/gomock"
)

// MockuserServiceProvider is a mock of userServiceProvider interface.
type MockuserServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceProviderMockRecorder
}

// MockuserServiceProviderMockRecorder is the mock recorder for MockuserServiceProvider.
type MockuserServiceProviderMockRecorder struct {
	mock *MockuserServiceProvider
}

// NewMockuserServiceProvider creates a new mock instance.
func NewMockuserServiceProvider(ctrl *gomock.Controller) *MockuserServiceProvider {
	mock := &MockuserServiceProvider{ctrl: ctrl}
	mock.recorder = &MockuserServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserServiceProvider) EXPECT() *MockuserServiceProviderMockRecorder {
	return m.recorder
}
